version: "3.8"

services:
  postgres:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=wellness
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
      - ./data/redis-dump:/var/lib/redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
  server:
    build:
      context: ./
      args:
        APP_ENVIRONMENT: local
    env_file: .env
    depends_on:
      - postgres
      - redis
    ports:
      - 8000:8000
