application:
  host: 0.0.0.0
  port: 8000
  graphql:
    path: "/graphql"
database:
  postgres:
    port: 5432
    username: "postgres"
    password: "password"
    database_name: "wellness"
  redis:
    port: 6379
    username: ""
    password: ""
