application:
  graphql:
    playground_enabled: true
    # TODO: set up development-container config
    # to enable playground while using docker connections to dbs
database:
  postgres:
    host: "localhost"
    require_ssl: false
  redis:
    host: "localhost"
