application:
  graphql:
    playground_enabled: true
  root_email: testuser@american.edu
  root_password: hunter2
database:
  postgres:
    host: "localhost"
    require_ssl: false
  redis:
    host: "localhost"
